class AppCollectionConstants {
  static const String utills = 'utills';
}

class AppConstants {
  static const String profilePicture = 'https://firebasestorage.googleapis.com/v0/b/love-story-434917.firebasestorage.app/o/sign_up_unicorn.png?alt=media';
}

class StringConstant {
  static const String blank = '';
  static const String appName = 'Love Story Unicorn';
  static const String welcomeToLoveStory = 'welcome to love story';
  static const String aRealLoveStoryMarriage = 'a real love story marriage';
  static const String onboardingFirst = 'a wholesome place to increase love in your life ';
  static const String onboardingSecond = 'get your happily ever after';
  static const String createAccount = 'create an account';
  static const String welcomeBack = 'Welcome back';
  static const String loginAccount = 'Login to your account';
  static const String signIn = 'Sign In';
  static const String logIn = 'Log In';
  static const String register = 'Register';
  static const String createYourAccount = 'Create your account';
  static const String signUp = 'Sign Up';
  static const String alreadyHaveAccount = 'already have an account?';
  static const String forgotPassword = 'Forgot Password?';
  static const String resetLink = 'sent Link';
  static const String orSignUpWith = 'or sign up with';
  static const String orSignInWith = 'or sign in with';
  static const String continueWithEmail = "don't have an account? sign up";
  static const String signInOption = 'already have an account? sign In';
  static const String signInWithEmail = 'Sign in with email';
  static const String usePhoneNumber = 'Use Phone Number';
  static const String termsOfUse = 'Terms of use';
  static const String privacyPolicy = 'Privacy Policy';
  static const String confirmYourEmail = 'Confirm your email';
  static const String name = 'name';
  static const String email = 'email';
  static const String number = 'number';
  static const String enterYourEmail = 'Email';
  static const String enterYourPassword = 'Password';
  static const String passwordHint = 'password: 8+ chars, upper/lowercase & symbol';
  static const String confirmEmail = 'Confirm email';
  static const String confirmPassword = 'Confirm password';
  static const String oneTimePassword = 'One Time Password';
  static const String confirmOneTimePassword = 'Confirm password';
  static const String otpMessage = 'We have sent a one time password to your email to confirm it’s your email';
  static const String emptyEmail = 'Please enter your email';
  static const String validEmail = 'Please enter a valid email';
  static const String validName = 'Please enter a valid name';
  static const String validLastName = 'Please enter a valid last name';
  static const String emptyName = 'Please enter your name';
  static const String emptyLastName = 'Please enter your lastName';
  static const String emptyDob = 'Please select date of birth';
  static const String selectDob = 'Select Date of Birth';
  static const String yourAge = 'Your Age : ';
  static const String retake = 'Retake';
  static const String take = 'Take';
  static const String continueText = 'Continue';
  static const String discoverYourConnection = 'Discover Romantic Matches';
  static const String years = 'years';
  static const String months = 'months';
  static const String days = 'days';
  static const String zeroYears = '0 years';
  static const String firstName = 'First Name';
  static const String profileDetails = 'Profile Details';
  static const String editProfile = 'Edit Profile';
  static const String lastName = 'Last Name';
  static const String enterFirstName = 'Enter First Name';
  static const String enterLastName = 'Enter Last Name';
  static const String maxAgeOlder = 'Max age older than you';
  static const String selectMaxOlder = 'Select Max Older Age';
  static const String maxAgeYounger = 'Max age younger than you';
  static const String selectMaxYounger = 'Select Max Younger Age';
  static const String countryName = 'country';
  static const String stateName = 'state';
  static const String cityName = 'city';
  static const String introVideo = 'Introduction Video';
  static const String connectedAccounts = 'connected accounts';
  static const String connectYourInstagram = 'connect your instagram account';
  static const String headshot = 'headshot';
  static const String fullBody = 'full body';
  static const String save = 'Save';
  static const String saveAnswers = 'Save answers';
  static const String iAmIn = 'Where am I ?';
  static const String lookingFor = 'Looking for a partner in';
  static const String partnerLocation = 'Partner Location';
  static const String iWant = 'I want';
  static const String iHave = 'I have';
  static const String iam = 'I am a';
  static const String looking = 'Looking for';
  static const String pickBreakers = 'Pick your deal breakers';
  static const String next = 'Next';
  static const String exitApp = 'Exit App';
  static const String exitAppDescription = 'Are you sure you want to exit the app?';
  static const String permissionDescription = 'Hey there! To make the magic happen, we need a bit of help from you. Granting access will allow app to work seamlessly and give you the best experience. We respect your privacy and promise to use your permissions responsibly no sneaky business, just pure awesomeness!';
  static const String permissionSubDescription = 'If you change your mind, you can always enable this in Settings. Let’s make it happen!';
  static const String notNow = 'Not Now';
  static const String goToSetting = 'Go to Settings';
  static const String subscription = 'Subscription';
  static const String subscriptionDescription = "please enter the secret code to access the app and get a 3 month free trial";
  static const String unknownTitle = 'Unknown Title';
  static const String priceZero = '\$0.00';
  static const String noDescription = 'No description available';
  static const String pleaseSelectPlan = 'Please select a plan or wait for products to load';
  static const String noPlanAvailable = 'We apologize for the inconvenience. Subscription plan is currently unavailable. Please check back later or explore other available options';
  static const String proceedToPayment = 'Proceed to Payment';
  static const String selectAnyOnePlan = 'Please select any one plan';
  static const String fiveToThirtySecond = "5-30-second video saying I'm open to this crazy little thing called love or something else";
  static const String potentialMatches = "potential match";
  static const String today = "Today";
  static const String yesterday = "Yesterday";
  static const String startConversation = "Start a conversation now with each other";
  static const String itsAMatch = "It's a match, Jake!";
  static const String requiredValidation = "This question is mandatory";
  static const String iHereby = "i hereby agree I am zoroastrian, single, and looking for love";
  static const String noMoreUsers = "No more users";
  static const String noMoreUsersMessage = "no matches found with your current filters. to review your filters you can click the button above. Please click the preferences button below to complete your profile and be ready for your future potential matches";
  static const String cancel = "Cancel";
  static const String yes = "Yes";
  static const String no = "No";
  static const String confirmation = "Confirmation";
  static const String location = "Location";
  static const String ageFilter = "Age Filter";
  static const String partnerAge = "Partner Age";
  static const String passwordRequirements = "Password Requirements";
  static const String okText = "Ok";
  static const String mandatoryPopup = "To increase your chances of finding a high quality partner please fill in these optional questions if they are important to you";


  ///
  static const String mandatoryQuestion = "mandatory questions";
  static const String optionalQuestion = "optional question";
  static const String selectOption = "selected option";
  static const String hintAnswer = "write your answer here";
  static const String potentialMatch = "Potential matches";
  static const String match = "Matches";

  static const String singleSelection = "singleSelection";
  static const String text = "text";
  static const String dropdown = "dropdown";
  static const String multiSelection = "multiSelection";

  static const String profile = "Profile";
  static const String apply = "Apply";
}
