// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqMOetxWCBpBEmRBr-Vw_b8UcnNVqylxc',
    appId: '1:588629962722:web:d8a0e6cbc6b0e749ff93bb',
    messagingSenderId: '588629962722',
    projectId: 'cc-event-8490c',
    authDomain: 'cc-event-8490c.firebaseapp.com',
    storageBucket: 'cc-event-8490c.firebasestorage.app',
    measurementId: 'G-W0YWXFWDB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQG0Mghzw6sIzxMsTki_79SRCjpMyoeuw',
    appId: '1:588629962722:android:523819f712a8868fff93bb',
    messagingSenderId: '588629962722',
    projectId: 'cc-event-8490c',
    storageBucket: 'cc-event-8490c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKYZBJuUx0nzQN5Oc9pMQ23EqhIC3xLDk',
    appId: '1:588629962722:ios:156995aa2a4a2a0bff93bb',
    messagingSenderId: '588629962722',
    projectId: 'cc-event-8490c',
    storageBucket: 'cc-event-8490c.firebasestorage.app',
    iosBundleId: 'com.event.management',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKYZBJuUx0nzQN5Oc9pMQ23EqhIC3xLDk',
    appId: '1:588629962722:ios:29462fb1d0da8323ff93bb',
    messagingSenderId: '588629962722',
    projectId: 'cc-event-8490c',
    storageBucket: 'cc-event-8490c.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqMOetxWCBpBEmRBr-Vw_b8UcnNVqylxc',
    appId: '1:588629962722:web:e1f77786a88a5639ff93bb',
    messagingSenderId: '588629962722',
    projectId: 'cc-event-8490c',
    authDomain: 'cc-event-8490c.firebaseapp.com',
    storageBucket: 'cc-event-8490c.firebasestorage.app',
    measurementId: 'G-E6N8JLHPYR',
  );
}
